name: Build and Push Python image to Google Cloud Platform
on: 
  push:
    branches: [ main ]

jobs: 
  build-push-gcr
    name: Build and Push to GCP 
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: myapp
      PROJECT_ID: my-pulumi-project-341020
    steps: 
    - name: checkout 
      uses: actions/checkout@v2
    
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets. SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true 

    - name: Build Docker Image 
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client 
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet

    - name: Push Docker Image to Container Registry(GCR)
      env: 
        GIT_TAG: v0.0.1
      run: 
        docker tag $IMAGE-NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE-NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG