name: Build and Push Python image to Google Cloud Platform
on: 
  push:
    branches: [ main ]

jobs: 
  build-push-gcr:
    name: Build and Push to GCP 
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: myapp
      PROJECT_ID: my-pulumi-project-341020
      
    permissions:
      contents: read
      id-token: write
      
    steps: 
    - name: checkout 
      uses: actions/checkout@v2
      
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: projects/336900529759/locations/global/workloadIdentityPools/my-pool/providers/my-provider
        service_account: my-service-account@my-pulumi-project-341020.iam.gserviceaccount.com

    - name: Build Docker Image 
      run: docker build -t $IMAGE_NAME:latest .
      
    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker northamerica-northeast1-docker.pkg.dev --quiet
        
    - name: Push Docker Image to Container Registry(GCR)
      uses: google-github-actions/setup-gcloud@v0
      env: 
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: |-
          docker tag $IMAGE-NAME:latest northamerica-northeast1-mamz/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE-NAME:latest northamerica-northeast1-mamz/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push northamerica-northeast1-mamz/$PROJECT_ID/$IMAGE_NAME:latest
          docker push northamerica-northeast1-mamz/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          
    - name: Push Docker Image to Container Registry(GCR)
      uses: google-github-actions/setup-gcloud@v0
      env: 
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        run: 
          docker tag $IMAGE_NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
          docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
          docker push northamerica-northeast1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        
        
